# List of service configurations.
services:
  - key: "service1"  # Unique identifier for the service.
    name: "My API Service"  # Name of the service.
    tags: # Optional list of tags to describe the service.
      - "api"
      - "production"
    repository: "https://github.com/my-api"  # Optional URL to the repository of the service.
    swagger_url: "https://my-api.com/swagger.json"  # Optional URL to the Swagger documentation.
    # swagger_file: "swagger_file_path.yaml"  # Alternatively, you can provide a file path instead of a URL.

# Directory where coverage results will be stored.
results_dir: "./coverage-results"  # This path is relative to the current working directory.

# File where the history of coverage results is saved.
history_file: "./coverage-history.json"  # This path is relative to the current working directory.
history_retention_limit: 30  # The maximum number of history records to keep.

# File paths for reports. These are optional, and if not set, reports will not be generated.
html_report_file: "./index.html"  # Path to the HTML report file.
json_report_file: "./coverage-report.json"  # Path to the JSON report file.
